# Generated by Django 4.2.7 on 2025-06-09 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Persona de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('company_address', models.TextField(verbose_name='Dirección')),
                ('company_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company_ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('proforma_prefix', models.CharField(default='PRF', max_length=10, verbose_name='Prefijo Proformas')),
                ('next_proforma_number', models.IntegerField(default=1, verbose_name='Siguiente # de Proforma')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.12, max_digits=5, verbose_name='Tasa de IVA')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Método')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('water', 'Monitoreo de Agua'), ('gas', 'Emisiones Gaseosas'), ('noise', 'Monitoreo de Ruido'), ('logistics', 'Logística')], max_length=20, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Método',
                'verbose_name_plural': 'Métodos',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Técnica')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('water', 'Monitoreo de Agua'), ('gas', 'Emisiones Gaseosas'), ('noise', 'Monitoreo de Ruido'), ('logistics', 'Logística')], max_length=20, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Técnica',
                'verbose_name_plural': 'Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proforma_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Proforma')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='draft', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100, verbose_name='Creado por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_app.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Parámetro')),
                ('category', models.CharField(choices=[('water', 'Monitoreo de Agua'), ('gas', 'Emisiones Gaseosas'), ('noise', 'Monitoreo de Ruido'), ('logistics', 'Logística')], max_length=20, verbose_name='Categoría')),
                ('default_unit', models.CharField(max_length=50, verbose_name='Unidad por Defecto')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_app.method', verbose_name='Método/Referencia')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_app.parameter', verbose_name='Parámetro')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_app.proforma', verbose_name='Proforma')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_app.technique', verbose_name='Técnica')),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
