# Generated by Django 4.2.7 on 2025-06-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='ruc',
            field=models.CharField(max_length=20, verbose_name='RUC'),
        ),
    ]
