# Generated by Django 4.2.7 on 2025-06-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0002_tipomuestra_alter_client_ruc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='method',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='technique',
        ),
        migrations.DeleteModel(
            name='CompanySettings',
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='client',
        ),
        migrations.DeleteModel(
            name='TipoMuestra',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Proforma',
        ),
        migrations.DeleteModel(
            name='Technique',
        ),
    ]
